services:
  - type: web
    name: stremio-vidlink-addon
    env: node
    plan: free
    rootDir: stremio-vidlink-addon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
